### ISSUE TITLE
Failed to load 'plugin.py' Python Path 

### ISSUE THREAD

**Issue by blooesky** [kofec/domoticz-AirPurifier#15]
Hi ,

I have this problem. When domoticz starts all is fine...but after a while...error. Especially if i want to update the plugin settings from domoticz and another situation when the plugin auto restart for data timeout.

2023-07-04 14:56:32.767 Error: Purificator Xiaomi: (AirPurifier) failed to load 'plugin.py', Python Path used was '/home/pi/domoticz/plugins/domoticz-AirPurifier/:/usr/lib/python39.zip:/usr/lib/python3.9:/usr/lib/python3.9/lib-dynload:/usr/local/lib/python3.9/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.9/dist-packages'.
2023-07-04 14:56:32.781 Error: Purificator Xiaomi: Traceback (most recent call last):
2023-07-04 14:56:32.781 Error: Purificator Xiaomi: File "/home/pi/domoticz/plugins/domoticz-AirPurifier/plugin.py", line 73, in <module>
2023-07-04 14:56:32.781 Error: Purificator Xiaomi: import miio.airpurifier
2023-07-04 14:56:32.781 Error: Purificator Xiaomi: File "/usr/local/lib/python3.9/dist-packages/miio/__init__.py", line 28, in <module>
2023-07-04 14:56:32.781 Error: Purificator Xiaomi: from miio.discovery import Discovery
2023-07-04 14:56:32.781 Error: Purificator Xiaomi: File "/usr/local/lib/python3.9/dist-packages/miio/discovery.py", line 8, in <module>
2023-07-04 14:56:32.781 Error: Purificator Xiaomi: import zeroconf
2023-07-04 14:56:32.781 Error: Purificator Xiaomi: File "/usr/local/lib/python3.9/dist-packages/zeroconf/__init__.py", line 25, in <module>
2023-07-04 14:56:32.781 Error: Purificator Xiaomi: from ._cache import DNSCache # noqa # import needed for backwards compat
2023-07-04 14:56:32.781 Error: Purificator Xiaomi: ImportError: Interpreter change detected - this module can only be loaded into one interpreter per process. 

Domoticz Beta v2023.1 (15375) an python 3.9 miio 0.4.5

Thanks

**Comment by manutremo** [comment]
This error is caused by one of the supporting libraries named PyO3 (possibly not in this library but in the python-miio one), which contains a limitation in that it can onyl be initialized once. That's why the plugin apparently works on start but then this error shows when the plugin restarts. The same happens when you have another plugin that uses the PyO3 module, or if you have two instances of the same plugin. That's my case since I have two purifiers and need to create two instances of the plugin. As of today the limitation is still there and the developer doesn't seem to be too motivated to fix it.

**Comment by kofec** [comment]
Fixed in 7f42e48 (v0.3.0). The plugin no longer imports python-miio inside Domoticz: every poll and every command runs `MyAir.py` in a separate `python3` process, so the PyO3 part of `cryptography` is never loaded into the Domoticz process. Restarting the plugin, running two instances (e.g. two purifiers) or other plugins that use `cryptography` (e.g. TinyTUYA) no longer break it. To update, run `git pull` in the plugin folder and click Update on the hardware. Tested with python-miio 0.5.12, cryptography 41.0.7, Python 3.11, Domoticz 2026.3.
